version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: 1234Abcd
      POSTGRES_DB: booking
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"