version: "3.9"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: 1234Abcd
      POSTGRES_DB: booking
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  app:
    build:
      dockerfile: Dockerfile
      target: runner
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_DRIVER: postgres
      DATABASE_URL: postgresql://booking:1234Abcd@postgres:5432
      REDIS_URL: redis://redis:6379